# Generated by Django 4.1.3 on 2022-12-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Emp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="Manager",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="Mobile",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="Name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="Office",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="Role",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
